apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0qif
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0qif
    app.kubernetes.io/part-of: ci1t-830-0058-app
  name: devfile-sample-0qif
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0qif
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0qif
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0058-tenant/ci1t-830-0058-app/devfile-sample-0qif@sha256:d57d11f8bc7642b350819fe9fe9ff7a25fc1724f6a891e0d239b9c0024d08c30
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
